# Generated by Django 5.0.6 on 2024-06-08 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaMae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('taxa_deposito', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('porcentagem_fixa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cpf_validos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContaFilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('conta_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contamae')),
            ],
        ),
        migrations.CreateModel(
            name='SplitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('requisito_cpf', models.BooleanField(default=False)),
                ('conta_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contamae')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
    ]
